// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SKCatalog.Models;

#nullable disable

namespace SKCatalog.Migrations
{
    [DbContext(typeof(SKCatalogContext))]
    partial class SKCatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SKCatalog.Models.SKClass", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("SKClasses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Capacity = 20,
                            Credit = 3,
                            Department = "Computer Science",
                            Name = "Internet Programming",
                            Number = "CPSC-8720-02"
                        },
                        new
                        {
                            CourseId = 2,
                            Capacity = 25,
                            Credit = 3,
                            Department = "Computer Science",
                            Name = "Database Systems",
                            Number = "CPSC-6710-01"
                        },
                        new
                        {
                            CourseId = 3,
                            Capacity = 30,
                            Credit = 3,
                            Department = "Health Informatica",
                            Name = "Health Data Management",
                            Number = "HINF-6100-01"
                        },
                        new
                        {
                            CourseId = 4,
                            Capacity = 35,
                            Credit = 4,
                            Department = "Match",
                            Name = "Calculus I",
                            Number = "MATH-2211-01"
                        },
                        new
                        {
                            CourseId = 5,
                            Capacity = 24,
                            Credit = 4,
                            Department = "Chemistry",
                            Name = "Organic Chemistry",
                            Number = "CHEM-3300-02"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
